version: "3.9"

services:
  inference:
    build:
      context: ..
      dockerfile: infra/docker/Dockerfile.inference
    ports:
      - "3001:3001"
    volumes:
      - ../artifacts:/app/artifacts
      - inference_data:/app/inference
    working_dir: /app

  dashboard:
    build:
      context: ..
      dockerfile: infra/docker/Dockerfile.dashboard
    ports:
      - "8080:80"
    depends_on:
      - inference

  training:
    build:
      context: ..
      dockerfile: infra/docker/Dockerfile.training
    volumes:
      - ../artifacts:/app/artifacts
      - inference_data:/app/inference
      - ../data:/app/data
    profiles: ["training"]

volumes:
  inference_data:
