# syntax=docker/dockerfile:1
# Build
FROM oven/bun:1 as builder
WORKDIR /app
COPY . .
RUN bun install --ci
RUN bun --cwd dashboard run build

# Runtime
FROM nginx:alpine
COPY --from=builder /app/dashboard/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
