name: CI/CD with DVC and MLflow

on:
  push:
    branches: [mlops-concepts, mlops-market-tools]
  pull_request:
    branches: [mlops-concepts, mlops-market-tools]

jobs:
  build-train-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Python Dependencies
        run: pip install "dvc[s3]" mlflow

      - name: Install JS Dependencies
        run: bun install

      - name: Configure DVC and S3 Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # Comente/descomente e configure conforme seu provedor S3
          # dvc remote modify my-remote endpointurl s3.amazonaws.com
          echo "DVC remote configured."

      - name: Pull Data from DVC
        run: dvc pull -r my-remote

      - name: Train model and Log to MLflow
        env:
          # Segredos para o MLflow se conectar ao seu servidor na Fly.io
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          # Se seu servidor MLflow precisar de autenticação, configure aqui
          # MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_USERNAME }}
          # MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_PASSWORD }}
        run: bun --cwd training run train

      - name: Push Artifacts to DVC
        run: dvc push -r my-remote

      - name: Build Dashboard
        run: bun --cwd dashboard run build

      - name: Upload Dashboard Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dashboard-dist
          path: dashboard/dist
